# Define the goal
bool goal_reached
---
# Define the result
geometry_msgs/PointStamped[] centroids
float64[] radiuses
string[] colors
float64[] goal_radiuses
geometry_msgs/PointStamped red_goal
geometry_msgs/PointStamped blue_goal
---
# Define a feedback message